# PCA (Principal Component Aanalusis)
 **USES**:
1. To improve algorithm performence by tranforming data.
2. To Make Algorithm very fast.
3. Use for visualization of data.
4. Use for Feature Extraction.

**Components**:
1. Mean
2. STD(Standard Deviation)
3. Covariance Matrix
4. Eigen value (λ),Eigen Vectors (v).

**Steps:**
1. calculate mean of each column
    - m = mean(data).
2. Substract each column by its mean value
    - scaled_dada = data - m
3. Covariance Matrix
    - v = cov(data)
4. calculate Eigen values and Eigen Vectors
    - values, vectors = eig(scaled_data)
5. Select longest k values by sorting.
    - B = (values,vectors)
6. Transform the data
    - B.T.dot(data) ---> Multiply


In [1]:
import numpy as np

In [2]:
# data for matrix
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
#mean of each column
M = np.mean(data.T,axis=1)
M

array([3., 4.])

In [4]:
# subtraction of mean from data
scaled_data = data - M
scaled_data

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [5]:
# covariance Matrix
v = np.cov(scaled_data.T)
v

array([[4., 4.],
       [4., 4.]])

In [6]:
# eigen value and eigen vectors
values, vectors = np.linalg.eig(v)
values,vectors

(array([8., 0.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [7]:
# project the data / tranformation the data
p = vectors.T.dot(scaled_data.T)

In [8]:
p

array([[-2.82842712,  0.        ,  2.82842712],
       [ 0.        ,  0.        ,  0.        ]])

In [9]:
p.T

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA()
pca.fit(scaled_data)
# Vectors
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [15]:
# values
print(pca.explained_variance_)
print(pca.explained_variance_ratio_) ##(8.+0. = 8.0) result = [8.//8.0,0.//8.]-->[1.,0.]-->ratio

[8. 0.]
[1. 0.]


In [ ]:
# transform
# o/p is like subtraction of mean from data

pca.transform(data)

In [ ]:
# PCA on Iris dataset
import pandas as pd
df  = pd.read_csv("D:\Python\ML\Datasets\Iris.csv")

In [ ]:

df.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Species'] =le.fit_transform(df['Species'])  

In [ ]:
df

In [ ]:
from sklearn.model_selection import train_test_split
x = df.drop(columns = ['Species'])
y = df['Species']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.fit_transform(xtest)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
xtrain = pca.fit_transform(xtrain)
xtest = pca.fit_transform(xtest)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model  = LogisticRegression()
model.fit(xtrain,ytrain)
ypred = model.predict(xtest)
from sklearn.metrics import accuracy_score,classification_report
print('ACCURACY: ',accuracy_score(ytest,ypred))


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(pca.explained_variance_ratio_,marker = 'o')
pca.components_
