In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("../Data/Ad_purchace.csv")

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})

In [ ]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0

In [ ]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
x=df.drop(columns=["User ID","Purchased"])
y=df["Purchased"]

In [ ]:
#train and test set
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5)
model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [ ]:
ypred=model.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [ ]:
#accuracy
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(ytest,ypred)
acc

0.825

In [ ]:
#confusion Matrix
cm=confusion_matrix(ytest,ypred)
cm

array([[51,  7],
       [ 7, 15]], dtype=int64)

In [ ]:
#classification_report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88        58
           1       0.68      0.68      0.68        22

    accuracy                           0.82        80
   macro avg       0.78      0.78      0.78        80
weighted avg       0.82      0.82      0.82        80



In [ ]:
#model with standard scaled data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

In [ ]:
model_sc=KNeighborsClassifier(n_neighbors=5)
model_sc.fit(xtrain,ytrain)
ypred=model_sc.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [ ]:
#test
acc=accuracy_score(ytest,ypred)
acc

0.925

In [ ]:
#train
acc=accuracy_score(ytrain,model_sc.predict(xtrain))
acc

0.909375

In [ ]:
#model Estimator
model=KNeighborsClassifier()

In [ ]:
#parameter grid
#n_neighbors,metric,weights
n_neighbors=range(1,31)
metric=["euclidean","manhattan","minkowski"]
weights=['uniform','distance']
grid={"n_neighbors":n_neighbors,"metric":metric,"weights":weights}

In [ ]:
#cv
from sklearn.model_selection import RepeatedStratifiedKFold
kfold=RepeatedStratifiedKFold(n_splits=5,n_repeats=3,random_state=1)

In [ ]:
#Grid Search cv
from sklearn.model_selection import GridSearchCV
grid_cv=GridSearchCV(estimator=model,param_grid=grid,cv=kfold,scoring="accuracy",n_jobs=1)

In [ ]:
#result
res=grid_cv.fit(xtrain,ytrain)

In [ ]:
res.best_params_

{'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}

In [ ]:
res.best_score_

0.8979166666666667

In [ ]:
#{'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}
model_best=KNeighborsClassifier(metric='manhattan',n_neighbors=11,weights='uniform')
model_best.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan', n_neighbors=11)

In [ ]:
ypred_best=model_best.predict(xtest)
ypred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1], dtype=int64)

In [ ]:
acc=accuracy_score(ytest,ypred_best)
acc

0.95